version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: laravel_web
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    networks:
      - laravel
    depends_on:
      - app

  postgres:
    image: postgres:13
    container_name: laravel_postgres
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: laravel_redis
    networks:
      - laravel
    ports:
      - "6379:6379"

networks:
  laravel:
    driver: bridge

volumes:
  pgdata:
    driver: local
